### ISSUE TITLE
Adapt html template into Angular app

### ISSUE THREAD

**Issue by ismtabo** [rookiesTeam/unixninja#3]
Move html template done by @javierprovecho into `angular/` directory and adapt it to appComponent template file.

**Comment by javierprovecho** [comment]
Issue assigned to @ismtabo and @Raikuro, added to April's 15th Angular 1st iteration milestone.

**Comment by javierprovecho** [comment]
Switched to Angular project

**Comment by ismtabo** [comment]
For live translation of permissions code from table to other values and vice versa, we have two possible options:

- **Class** `Permissions` which implements all behavior and translations, as you can update it from all possible attributes: 
    - Table
    - Hexadecimal / binary values
    - Verbose
- **Pipe** `permissions` used at view scopes to translate binary value (string representation of binary value) to other values.

Which do you think is the good way to go? Have you got any other idea?

**Comment by ismtabo** [comment]
@Raikuro @javierprovecho answer, please.

**Comment by Raikuro** [comment]
As I was assigned to Angular related to live translation, I decided to do as a class, because it gives a better functionality and I think it would be easier to support it.

**Comment by ismtabo** [comment]
Issue finished. PR #6
